name: Linux VNC via Tailscale

on: [push]

jobs:
  vnc-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hour max

    steps:
    - name: Install Desktop Environment and VNC Server
      run: |
        sudo apt-get update
        # تعطيل أي شاشات تفاعلية أثناء التثبيت
        export DEBIAN_FRONTEND=noninteractive
        # تثبيت بيئة سطح مكتب خفيفة (XFCE) وخادم VNC
        sudo apt-get install -y xfce4 xfce4-goodies tigervnc-standalone-server dbus-x11

    - name: Configure VNC Server
      env:
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        if [ -z "$VNC_PASSWORD" ]; then
          echo "::error:: VNC_PASSWORD secret is not set."
          exit 1
        fi
        
        # إنشاء مجلد إعدادات VNC
        mkdir -p /home/runner/.vnc
        
        # حفظ كلمة المرور المشفرة
        echo "$VNC_PASSWORD" | vncpasswd -f > /home/runner/.vnc/passwd
        chmod 600 /home/runner/.vnc/passwd
        
        # --==[ التعديل هنا ]==--
        # استخدام 'echo' لإنشاء ملف xstartup لتجنب أخطاء YAML
        echo "#!/bin/sh" > /home/runner/.vnc/xstartup
        echo "unset SESSION_MANAGER" >> /home/runner/.vnc/xstartup
        echo "unset DBUS_SESSION_BUS_ADDRESS" >> /home/runner/.vnc/xstartup
        echo "exec startxfce4" >> /home/runner/.vnc/xstartup
        # --==[ نهاية التعديل ]==--
        
        chmod +x /home/runner/.vnc/xstartup

    - name: Start VNC Server in background
      run: |
        # تشغيل خادم VNC على الشاشة :1 (التي تستخدم البورت 5901)
        vncserver :1 -localhost no -geometry 1280x800 -depth 24

    - name: Install and Start Tailscale
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        if [ -z "$TAILSCALE_AUTH_KEY" ]; then
          echo "::error:: TAILSCALE_AUTH_KEY secret is not set."
          exit 1
        fi
        
        # تحميل وتثبيت Tailscale
        curl -fsSL https://tailscale.com/install.sh | sudo sh
        
        # تشغيل Tailscale
        sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY
        
        echo "Waiting 10 seconds for Tailscale to connect..."
        sleep 10
        
        TS_IP=$(tailscale ip -4)
        
        if [ -z "$TS_IP" ]; then
          echo "::error::Failed to get Tailscale IP."
          sudo tailscale status
          exit 1
        fi

        echo "=========================================="
        echo "||         VNC CONNECTION DETAILS         ||"
        echo "=========================================="
        echo "Address (Tailscale IP + Port):"
        echo ""
        echo "$TS_IP:5901"
        echo ""
        echo "Password: [Your VNC_PASSWORD Secret]"
        echo "=========================================="
        echo "1. Connect your local device to Tailscale."
        echo "2. Open your VNC client (e.g., RealVNC, TightVNC)."
        echo "3. Connect to: $TS_IP:5901"
        echo "=========================================="

    - name: Keep alive
      run: tail -f /dev/null
