name: Linux SSH via Tailscale

on: [push]

jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hour max

    steps:
    - name: Download and install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sudo sh

    - name: Start Tailscale and enable SSH
      env:
        # تأكد من إضافة هذا الـ Secret في إعدادات المستودع
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        if [ -z "$TAILSCALE_AUTH_KEY" ]; then
          echo "::error:: TAILSCALE_AUTH_KEY secret is not set."
          exit 1
        fi
        
        # تشغيل Tailscale والإعلان عن خدمة SSH (الأمر --ssh هو ميزة رائعة)
        sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY --ssh
        
        echo "Waiting 10 seconds for Tailscale to connect..."
        sleep 10
        
        # جلب عنوان IP الخاص بـ Tailscale
        TS_IP=$(tailscale ip -4)
        
        if [ -z "$TS_IP" ]; then
          echo "::error::Failed to get Tailscale IP."
          sudo tailscale status
          exit 1
        fi

        echo "=========================================="
        echo "||         SSH CONNECTION DETAILS         ||"
        echo "=========================================="
        echo "To connect, run this command on your local machine"
        echo "(after logging into Tailscale locally):"
        echo ""
        echo "ssh runner@$TS_IP"
        echo ""
        echo "The GitHub user is 'runner'"
        echo "=========================================="

    - name: Keep alive
      # هذا الأمر يبقي الـ job شغالة
      run: tail -f /dev/null
