name: Windows RDP via Tailscale

on: [push]

jobs:
  rdp-setup:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hour max

    steps:
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Create RDP User
      run: |
        net user kamel007 kamel007 /add /Y
        net localgroup administrators kamel007 /add
        reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList" /v kamel007 /t REG_DWORD /d 0 /f

    - name: Download and install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
        # Use Start-Process -Wait to ensure installation finishes before proceeding
        Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/S" -Wait

    - name: Start Tailscale and display connection info
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        if (-not $env:TAILSCALE_AUTH_KEY) {
          Write-Error "::error:: TAILSCALE_AUTH_KEY secret is not set."
          exit 1
        }
        
        # Start Tailscale (call directly, it should be in PATH)
        tailscale.exe up --authkey=$env:TAILSCALE_AUTH_KEY
        
        # Wait for connection
        Write-Output "Waiting 10 seconds for Tailscale to connect..."
        Start-Sleep -Seconds 10
        
        # Get Tailscale IP
        $tsIp = tailscale.exe ip -4
        
        if (-not $tsIp) {
          Write-Error "::error::Failed to get Tailscale IP after 10 seconds."
          tailscale.exe status
          exit 1
        }

        Write-Output "=========================================="
        Write-Output "||        RDP CONNECTION DETAILS        ||"
        Write-Output "=========================================="
        Write-Output "Address (Tailscale IP): $tsIp"
        Write-Output "Username: kamel007"
        Write-Output "Password: kamel007"
        Write-Output "------------------------------------------"
        Write-Output "1. Connect your local device to your Tailnet"
        Write-Output "2. Open Remote Desktop (mstsc)"
        Write-Output "3. Connect to: $tsIp"
        Write-Output "=========================================="

        # Keep alive
        while ($true) { Start-Sleep -Seconds 300 }

    - name: Force cleanup
      if: always()
      run: |
        try {
          tailscale.exe down
        } catch {
          Write-Warning "Tailscale cleanup failed."
        }
